### ISSUE TITLE
Error in quick start example of "SubscriberApp "

### ISSUE THREAD

**Issue by bibistellar** [lambdaprime/jrosclient#1] opened 2024-03-07 13:34 UTC
Hello,I followed the guide and tried to run the example of "SubscriberApp" ,it worked (java client got the data from publisher) but the programme kept throwing error everytime after it got the data.I don't know whether it is normal.I have tried in wsl2 and Linux and got the same error.Here is my environment and the things I have done:
Environment:Ubuntu 22.04,ROS2 humble(installed followed by the official guidance),jdk17
Steps:
a) create the SubscriberApp.java:
```
package com.example;

import id.jros2client.JRos2ClientFactory;
import id.jrosclient.TopicSubscriber;
import id.jrosmessages.std_msgs.StringMessage;


public class SubscriberApp {

    public static void main(String[] args) throws Exception {
        var client = new JRos2ClientFactory().createClient();
        var topicName = "/helloRos";
        // register a new subscriber
        client.subscribe(new TopicSubscriber<>(StringMessage.class, topicName) {
            @Override
            public void onNext(StringMessage item) {
                System.out.println(item);
                // request next message
                getSubscription().get().request(1);
            }
        });

        // usually we need to close client once we are done
        // but here we keep it open so that subscriber will keep
        // printing messages indefinitely
    }
}
```
b)run the command to publish meg
```
ros2 topic pub -r 10 helloRos std_msgs/String 'data: "hello there"'
```
c)run java code and got the data and error:
```
{ "data": "hello there" }
3月 07, 2024 9:16:37 下午 pinorobotics.rtpstalk.impl.spec.userdata.DataReader#1586845078-00000104
严重: Cannot open connection to remote writer on { "transportType": "LOCATOR_KIND_INVALID", "port": "0", "address": "/0.0.0.0" }
java.lang.RuntimeException: Cannot open connection to remote writer on { "transportType": "LOCATOR_KIND_INVALID", "port": "0", "address": "/0.0.0.0" }
        at pinorobotics.rtpstalk.impl.spec.behavior.reader.WriterProxy.getDataChannel(WriterProxy.java:179)
        at pinorobotics.rtpstalk.impl.behavior.reader.WriterHeartbeatProcessor.lambda$ack$0(WriterHeartbeatProcessor.java:115)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at pinorobotics.rtpstalk.impl.behavior.reader.WriterHeartbeatProcessor.ack(WriterHeartbeatProcessor.java:115)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at pinorobotics.rtpstalk.impl.spec.behavior.reader.StatefullReliableRtpsReader.process(StatefullReliableRtpsReader.java:221)
        at pinorobotics.rtpstalk.impl.spec.behavior.reader.RtpsReader.onNext(RtpsReader.java:241)
        at pinorobotics.rtpstalk.impl.spec.behavior.reader.RtpsReader.onNext(RtpsReader.java:80)
        at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeNext(Unknown Source)
        at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.takeItems(Unknown Source)
        at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consume(Unknown Source)
        at java.base/java.util.concurrent.SubmissionPublisher$ConsumerTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Can't connect to port 0
        at java.base/sun.nio.ch.DatagramChannelImpl.connect(Unknown Source)
        at java.base/sun.nio.ch.DatagramChannelImpl.connect(Unknown Source)
        at pinorobotics.rtpstalk.impl.spec.transport.DataChannelFactory.connect(DataChannelFactory.java:124)
        at pinorobotics.rtpstalk.impl.spec.behavior.reader.WriterProxy.getDataChannel(WriterProxy.java:177)
        ... 22 more
```

What I ecpected:
There should be only data,no error.

Maybe you can give me some advice,thank you.

**Comment by lambdaprime** [comment] 2024-03-08 02:33
Hi @bibistellar ,

Thanks for trying **jrosclient**

Closing as a duplicate of lambdaprime/jros2client#10. Please see it for more information.

Regards,

**Closed as completed by lambdaprime** 2024-03-08 02:33 UTC
